### ISSUE TITLE
Invalide optimisation example

### ISSUE THREAD

**Issue by twirrim** [kevinconway/pycc#11] opened 2018-09-05 04:57 UTC
This only seems to happen with python3?  Original:
```
 $ cat test.py
#!/usr/bin/env python

foo = dict()

foo['bar'] = "baz"

print("{bar}".format(**foo))

$ pycc-transform --source test.py
$ cat test_optimized.py
foo = dict()
foo['bar'] = 'baz'
print('{bar}'.format(None=foo))

$ python test_optimized.py
  File "test_optimized.py", line 3
    print('{bar}'.format(None=foo))
                        ^
SyntaxError: keyword can't be an expression

```
With python2 the optimised version is pretty much as expected:
```
$ cat test_optimized.py
foo = dict()
foo['bar'] = 'baz'
print '{bar}'.format(**foo)
```

**Comment by kevinconway** [comment] 2018-09-05 13:00
I believe this is due to changes in the AST for Python3 that `astkit` has not accounted for yet. There are two choices for output, one being bytecode and the other being source code. The bytecode option is handled by the Python standard library so it _should_ always be accurate so long as the optimizers are behaving correctly.

The source code option, however, leverages the `astkit` functions to regenerate source from an AST. It looks like there was a change to the AST for `kwargs` in Python3.5 (https://greentreesnakes.readthedocs.io/en/latest/nodes.html#Call) that may be the cause.

In the case of your example, no optimizers are actually running. All optimizers are off by default until they are enabled by name in the CLI. It's because of this that I strongly suspect `astkit` as the cause. Your example should always result in an exact copy of the source (plus or minus some formatting changes).

**Comment by kevinconway** [comment] 2018-09-12 07:33
I'm going to close this issue as there is not much we can do in this project to resolve the problem. I'd recommend opening a ticket and/or making a PR to the `astkit` project to add support for the new Python3.5 ast nodes if you end up requiring Python3.5 support. Otherwise, all of the versions listed in the `tox.ini` should be able to process your example and produce a valid Python source file as an output.

**Closed as completed by kevinconway** 2018-09-12 07:33 UTC
